{% set name = "momentum" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookincubator/momentum/archive/v{{ version }}.tar.gz
    sha256: f37bb8288b873de3b804c367eadeec81c02bff2ceff470f35a9427ed4b426bfe

build:
  number: 0
  skip: true  # [py<310]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - ceres-solver
    - drjit-cpp
    - gflags
    - librerun-sdk <0.17
    - openfbx
    - python
    - re2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - libboost-devel
    - cmake
    - ninja  # [not win]
    - python
  host:
    - ceres-solver
    - cli11
    - dispenso
    - drjit-cpp
    - eigen
    - ezc3d
    - fmt
    - fx-gltf
    - librerun-sdk <0.17
    - ms-gsl
    - nlohmann_json
    - openfbx
    - python  # [linux]
    - re2
    - sophus
    - spdlog
  run:
    - dispenso
    - gflags
    - libdeflate
    - python  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/cmake/momentum/momentum-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\momentum\\momentum-config.cmake exit 1  # [win]

about:
  home: https://facebookincubator.github.io/momentum/
  summary: 'A library for human kinematic motion and numerical optimization solvers to apply human motion'
  description: |
    A library for human kinematic motion and numerical optimization solvers to apply human motion
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookincubator/momentum

extra:
  recipe-maintainers:
    - jeongseok-meta
