azure:
  free_disk_space: true
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\Miniforge
bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
